List<Map<String, dynamic>> subCategory = [
  {
    "Text": "MAN",
  },
  {
    "Text": "WOMAN",
  },
  {
    "Text": "KIDS",
  },
  {
    "Text": "SHIRTS",
  },
  {
    "Text": "WATCHES",
  },
  {"Text": "BELTS"}
];
List<Map<String, dynamic>> allProducts = [
  {
    'id': 'cs-1',
    'name': 'Mens Cotton Shirt',
    'price': 899.00,
    'rating': 3.7,
    'catagory': "Casual Shirt",
    'disscount': 10,
    'thumbnail': 'https://m.media-amazon.com/images/I/71IK8SdP0qL.SY879.jpg',
    'brandName': 'ETA',
    'stock': 65,
    'cata': 'Casual Shirt',
    'discription':
        'Invest in stylish separates for a dapper look like this resort-fitting light mauve shirt from ETA.',
    'img': [
      'https://m.media-amazon.com/images/I/71IK8SdP0qL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71lYn+gt83L.SY879.jpg',
      'https://m.media-amazon.com/images/I/81QgU+tJsBL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81cZgFQy6GL.SY879.jpg',
    ],
  },
  {
    'id': 'cs-2',
    'name': 'Men Printed Regular Fit Casual Shirt',
    'price': 1499.00,
    'rating': 4.7,
    'catagory': "Casual Shirt",
    'disscount': 7,
    'thumbnail': 'https://m.media-amazon.com/images/I/81-JAkrN1sL.SY879.jpg',
    'brandName': 'WES',
    'stock': 35,
    'cata': 'Casual Shirt',
    'discription':
        'A versatile investment for your outdoor rotation is this dark blue shirt from WES Casuals.',
    'img': [
      'https://m.media-amazon.com/images/I/81-JAkrN1sL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81sdg6h4LGL.SY879.jpg',
      'https://m.media-amazon.com/images/I/711I3VGeDAL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81wkF5tEeWL.SY879.jpg',
    ],
  },
  {
    'id': 'cs-3',
    'name': 'Off-White Floral Printed Moni Resort Fit Shirt',
    'price': 1299.00,
    'catagory': "Casual Shirt",
    'rating': 3.7,
    'disscount': 15,
    'thumbnail': 'https://m.media-amazon.com/images/I/51oqHcH9mcL.SY879.jpg',
    'brandName': 'ETA',
    'stock': 89,
    'cata': 'Casual Shirt',
    'discription':
        'Elevate your summer wardrobe with this off-white floral printed moni resort fit shirt from ETA.',
    'img': [
      'https://m.media-amazon.com/images/I/81DAgwETgpL.SY879.jpg',
      'https://m.media-amazon.com/images/I/51oqHcH9mcL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71YWTgu+U2L.SY879.jpg',
      'https://m.media-amazon.com/images/I/51SkyEi+8YL.SY879.jpg',
    ],
  },
  {
    'id': 'cs-4',
    'name': 'Light Teal Stripe-Print Resort-Fit Shirt',
    'price': 999.00,
    'rating': 3.7,
    'catagory': "Casual Shirt",
    'disscount': 6,
    'thumbnail': 'https://m.media-amazon.com/images/I/61DGAlvxRLL.SY879.jpg',
    'brandName': 'ETA',
    'stock': 77,
    'cata': 'Casual Shirt',
    'discription':
        'Made from pure cotton to keep you comfortable all day, this light teal shirt by ETA.',
    'img': [
      'https://m.media-amazon.com/images/I/61DGAlvxRLL.SY879.jpg',
      'https://m.media-amazon.com/images/I/61UO+FOQNWL.SY879.jpg',
      'https://m.media-amazon.com/images/I/613Y6xzny8L.SY879.jpg',
      'https://m.media-amazon.com/images/I/81Hhhy37piL.SY879.jpg',
    ],
  },
  {
    'id': 'cs-5',
    'name': 'Leriya Fashion Textured Shirts ',
    'price': 1299.00,
    'rating': 4.2,
    'catagory': "Casual Shirt",
    'disscount': 16,
    'thumbnail': 'https://m.media-amazon.com/images/I/715Gcc34mvL.SY879.jpg',
    'brandName': 'NUON',
    'stock': 77,
    'cata': 'Casual Shirt',
    'discription':
        'Primed to make its debut in your summer edit is this blue shirt from Nuon.',
    'img': [
      'https://m.media-amazon.com/images/I/715Gcc34mvL.SY879.jpg',
      'https://m.media-amazon.com/images/I/713ei0-oEWL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71+52skQhGL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71CUPY54jML.SY879.jpg',
    ],
  },
  {
    'id': 'fs-1',
    'name': 'Scott International Shirt for Men',
    'price': 999.00,
    'rating': 2.7,
    'disscount': 10,
    'thumbnail': 'https://m.media-amazon.com/images/I/51X5JPMP1BL.SY879.jpg',
    'brandName': 'WES',
    'stock': 65,
    'cata': 'Formal Shirt',
    'catagory': "Formal Shirt",
    'discription':
        'A sophisticated update to your nine-to-five repertoire is this dark brown shirt from WES Formals.',
    'img': [
      'https://m.media-amazon.com/images/I/51X5JPMP1BL.SY879.jpg',
      'https://m.media-amazon.com/images/I/61oGRGvJqCL.SX679.jpg',
      'https://m.media-amazon.com/images/I/41xGhXjR3iL.SY879.jpg',
      'https://m.media-amazon.com/images/I/51crZbzrywL.SX679.jpg',
    ],
  },
  {
    'id': 'fs-2',
    'name': 'Formals Indigo Ultra Slim-Fit Shirt',
    'price': 999.00,
    'rating': 3.7,
    'disscount': 5,
    'catagory': "Formal Shirt",
    'thumbnail': 'https://m.media-amazon.com/images/I/61Ye3teTXsL.SY879.jpg',
    'brandName': 'ETA',
    'stock': 55,
    'cata': 'Formal Shirt',
    'discription':
        'A sophisticated update to your nine-to-five repertoire is this dark brown shirt from WES Formals.',
    'img': [
      'https://m.media-amazon.com/images/I/61Ye3teTXsL.SY879.jpg',
      'https://m.media-amazon.com/images/I/51y55SQgiVL.SY879.jpg',
      'https://m.media-amazon.com/images/I/6190PofOdDL.SY879.jpg',
      'https://m.media-amazon.com/images/I/51Nr1JEm1AL.SY879.jpg',
    ],
  },
  {
    'id': 'fs-3',
    'name': 'GRECIANS Men Solid Regular Fit Casual Shirt ',
    'price': 999.00,
    'rating': 4.7,
    'disscount': 15,
    'catagory': "Formal Shirt",
    'thumbnail': 'https://m.media-amazon.com/images/I/71QrkXBPABL.SY879.jpg',
    'brandName': 'WES',
    'stock': 55,
    'cata': 'Formal Shirt',
    'discription': 'Elevate your formal attire with the WES Formals shirt.',
    'img': [
      'https://m.media-amazon.com/images/I/71QrkXBPABL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71CUPY54jML.SY879.jpg',
      'https://m.media-amazon.com/images/I/71EqoV0fyGL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71qFgTzGboL.SY879.jpg',
    ],
  },
  {
    'id': 'fs-4',
    'name': 'Formals Plain Dark Teal Ultra Slim Fit Shirt',
    'price': 999.00,
    'rating': 3.2,
    'catagory': "Formal Shirt",
    'disscount': 12,
    'thumbnail': 'https://m.media-amazon.com/images/I/51K7WkEi-JL.SY879.jpg',
    'brandName': 'WES',
    'stock': 45,
    'cata': 'Formal Shirt',
    'discription': 'Elevate your formal attire with the WES Formals shirt.',
    'img': [
      'https://m.media-amazon.com/images/I/51l8sJPhGAL.SY879.jpg',
      'https://m.media-amazon.com/images/I/61VP2-YuYzL.SY879.jpg',
      'https://m.media-amazon.com/images/I/61NcvZj5O+L.SY879.jpg',
      'https://m.media-amazon.com/images/I/61NcvZj5O+L.SY879.jpgs',
    ],
  },
  {
    'id': 'fs-5',
    'name': 'Symbol Mens Formal Shirt',
    'price': 1499.00,
    'rating': 4.2,
    'catagory': "Formal Shirt",
    'disscount': 15,
    'thumbnail': 'https://m.media-amazon.com/images/I/81uXfQSwPFL.SY879.jpg',
    'brandName': 'WES',
    'stock': 45,
    'cata': 'Formal Shirt',
    'discription': 'Elevate your formal attire with the WES Formals shirt.',
    'img': [
      'https://m.media-amazon.com/images/I/81uXfQSwPFL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81II8K7RFeL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81UdXKRvdWL.SY879.jpg',
      'https://m.media-amazon.com/images/I/91kRNDaHJzL.SY879.jpg',
    ],
  },
  {
    'id': 'ts-1',
    'name': 'Mens Cotton Rich Polo T Shirt',
    'price': 899.00,
    'rating': 3.2,
    'disscount': 10,
    'thumbnail': 'https://m.media-amazon.com/images/I/713n+TxyfCL.SY879.jpg',
    'brandName': 'ETA',
    'stock': 59,
    'cata': 'T-Shirt',
    'catagory': "T-Shirt",
    'discription':
        'Made from soft and breathable fabric, this tee offers a relaxed and comfortable fit.',
    'img': [
      'https://m.media-amazon.com/images/I/713n+TxyfCL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81-IrK4ZyCL.SY879.jpg',
      'https://m.media-amazon.com/images/I/91pc-g7POZL.SY879.jpg',
      'https://m.media-amazon.com/images/I/91S76xHas-L.SY879.jpg',
    ],
  },
  {
    'id': 'ts-2',
    'name': 'Taupe Alan Relaxed Fit T-Shirt',
    'catagory': "T-Shirt",
    'price': 699.00,
    'rating': 4.2,
    'disscount': 3,
    'thumbnail':
        'https://m.media-amazon.com/images/I/71AEwEupFuL.AC_UL480_FMwebp_QL65.jpg',
    'brandName': 'NUON',
    'stock': 59,
    'cata': 'T-Shirt',
    'discription':
        'Elevate your casual wardrobe with this taupe alan relaxed fit t-shirt from Nuon.',
    'img': [
      'https://m.media-amazon.com/images/I/71AEwEupFuL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81DPQamPpaL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81yLE0JtuSL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81A5lJt8H5L.SY879.jpg',
    ],
  },
  {
    'id': 'ts-3',
    'name': 'Allen Solly Men Regular Fit Polo',
    'catagory': "T-Shirt",
    'price': 799.00,
    'rating': 4.6,
    'disscount': 5,
    'thumbnail': 'https://m.media-amazon.com/images/I/81YQK2fT9dL.SY879.jpg',
    'brandName': 'ETA',
    'stock': 77,
    'cata': 'T-Shirt',
    'discription':
        'Elevate your casual style with this emerald green boss slim fit t-shirt by ETA.',
    'img': [
      'https://m.media-amazon.com/images/I/81uWc0wAE+L.SY879.jpg',
      'https://m.media-amazon.com/images/I/811UpS+tTcL.SY879.jpg',
      'https://m.media-amazon.com/images/I/91Fv84Nu78L.SY879.jpg',
      'https://m.media-amazon.com/images/I/A1RkOabKziL.SY879.jpg',
    ],
  },
  {
    'id': 'ts-4',
    'name': 'Ola Black Printed Slim Fit T-Shirt',
    'catagory': "T-Shirt",
    'price': 699.00,
    'rating': 3.6,
    'disscount': 7,
    'thumbnail':
        'https://m.media-amazon.com/images/I/71ZYRN7kFKL.AC_UL480_FMwebp_QL65.jpg',
    'brandName': 'NUON',
    'stock': 89,
    'cata': 'T-Shirt',
    'discription':
        'This t-shirt features a clean off-white color with a stylish and modern print.',
    'img': [
      'https://m.media-amazon.com/images/I/71ZYRN7kFKL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71Nlmjz6MZL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81OwJMpPZ4L.SY879.jpg',
      'https://m.media-amazon.com/images/I/71GiCtJQswL.SY879.jpg',
    ],
  },
  {
    'id': 'ts-5',
    'name': 'Tim Off-White Printed Slim Fit T-Shirt',
    'catagory': "T-Shirt",
    'price': 699.00,
    'rating': 2.6,
    'disscount': 7,
    'thumbnail': 'https://m.media-amazon.com/images/I/613KABeTdwL.SY879.jpg',
    'brandName': 'NUON',
    'stock': 89,
    'cata': 'T-Shirt',
    'discription':
        'Add a touch of sophistication to your outfit with this tim off-white printed slim fit t-shirt by Nuon. ',
    'img': [
      'https://m.media-amazon.com/images/I/613KABeTdwL.SY879.jpg',
      'https://m.media-amazon.com/images/I/51OVMS7p9CL.SY879.jpg',
      'https://m.media-amazon.com/images/I/51OVMS7p9CL.SY879.jpg',
      'https://m.media-amazon.com/images/I/613KABeTdwL.SY879.jpg',
    ],
  },
  {
    'id': 'ss-1',
    'name': 'Qube By Fort Collins Men ',
    'price': 1499.00,
    'rating': 4.6,
    'disscount': 10,
    'thumbnail': 'https://m.media-amazon.com/images/I/81CgDvttFnS.SY879.jpg',
    'brandName': 'STUDIOFIT',
    'stock': 99,
    'catagory': "Sweatshirts",
    'cata': 'Sweatshirts',
    'discription':
        'Stay stylish and comfortable with this tie and dye orange relaxed ',
    'img': [
      'https://m.media-amazon.com/images/I/81CgDvttFnS.SY879.jpg',
      'https://m.media-amazon.com/images/I/81YZa0qQ94S.SY879.jpg',
      'https://m.media-amazon.com/images/I/91CHGlEZNfS.SY879.jpg',
      'https://m.media-amazon.com/images/I/61DSg-nxnNS.SY879.jpg',
    ],
  },
  {
    'id': 'ss-2',
    'name': 'AUSK Round Neck Full Sleeve T-Shirt for Men',
    'price': 1299.00,
    'rating': 3.6,
    'catagory': "Sweatshirts",
    'disscount': 15,
    'thumbnail': 'https://m.media-amazon.com/images/I/41W1WEP6nsL.jpg',
    'brandName': 'ETA',
    'stock': 58,
    'cata': 'Sweatshirts',
    'discription':
        'Enhance your casual attire with the Studio Mens Off White half sleeves hooded t-shirt.',
    'img': [
      'https://m.media-amazon.com/images/I/41W1WEP6nsL.jpg',
      'https://m.media-amazon.com/images/I/41N8b29W8mL.jpg',
      'https://m.media-amazon.com/images/I/41K9J4v2TRL.jpg',
      'https://m.media-amazon.com/images/I/51dxfdTVcXL.jpg',
    ],
  },
  {
    'id': 'ss-3',
    'name': 'Jc Jump Cuts Men Slim Fit T-Shirt',
    'price': 1299.00,
    'catagory': "Sweatshirts",
    'rating': 4.2,
    'disscount': 7,
    'thumbnail': 'https://m.media-amazon.com/images/I/61OAA70RlgL.SY879.jpg',
    'brandName': 'STUDIOFIT',
    'stock': 59,
    'cata': 'Sweatshirts',
    'discription':
        'Add a generous dose of style to your look with this indigo sweatshirt from Studiofit.',
    'img': [
      'https://m.media-amazon.com/images/I/61OAA70RlgL.SY879.jpg',
      'https://m.media-amazon.com/images/I/61B-NKpUVTL.SY879.jpg',
      'https://m.media-amazon.com/images/I/91N4hsdgwWL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71oczf6Lq+L.SY879.jpg',
    ],
  },
  {
    'id': 'ss-4',
    'catagory': "Sweatshirts",
    'name': 'Jump Cuts Mens Printed Polo Neck ',
    'price': 1399.00,
    'rating': 3,
    'disscount': 10,
    'thumbnail': 'https://m.media-amazon.com/images/I/61NrFCvC-pL.SY879.jpg',
    'brandName': 'STUDIO',
    'stock': 63,
    'cata': 'Sweatshirts',
    'discription':
        'This indigo sweatshirt from Studiofit offers an understated look with endless appeal.',
    'img': [
      'https://m.media-amazon.com/images/I/61NrFCvC-pL.SY879.jpg',
      'https://m.media-amazon.com/images/I/615X8hNewYL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71WEfi+85OL.SY879.jpg',
      'https://m.media-amazon.com/images/I/61NrFCvC-pL.SY879.jpg',
    ],
  },
  {
    'id': 'ss-5',
    'name': 'Ly mio Men Sweatshirts  Sweatshirts for Men ',
    'catagory': "Sweatshirts",
    'price': 999.00,
    'rating': 3.5,
    'disscount': 15,
    'thumbnail': 'https://m.media-amazon.com/images/I/612nb6YTRdL.SY879.jpg',
    'brandName': 'WES',
    'stock': 54,
    'cata': 'Sweatshirts',
    'discription':
        'Stay cozy and stylish with this sweatshirt from WES Casuals.',
    'img': [
      'https://m.media-amazon.com/images/I/612nb6YTRdL.SY879.jpg',
      'https://m.media-amazon.com/images/I/81ANuDL-+cL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71A8oxmVzYL.SY879.jpg',
      'https://m.media-amazon.com/images/I/71J1mELXb3L.SY879.jpg',
    ],
  },
];

List cart  = [];